// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwntQrhauI_HeKriZRIE8StjLRi6D-uKg',
    appId: '1:742438237263:web:086981188376fe611f263a',
    messagingSenderId: '742438237263',
    projectId: 'nutrilens-9d14f',
    authDomain: 'nutrilens-9d14f.firebaseapp.com',
    storageBucket: 'nutrilens-9d14f.appspot.com',
    measurementId: 'G-CMC7QR1342',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4kHTMDcBKJZiWzFRRE2bdQ1I1yn-vqA',
    appId: '1:742438237263:android:800aaf4499c45abe1f263a',
    messagingSenderId: '742438237263',
    projectId: 'nutrilens-9d14f',
    storageBucket: 'nutrilens-9d14f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkbpBsjY_EoKr4HzLEDnOzzn5tXEw8-kQ',
    appId: '1:742438237263:ios:e07bb602ad3ab2821f263a',
    messagingSenderId: '742438237263',
    projectId: 'nutrilens-9d14f',
    storageBucket: 'nutrilens-9d14f.appspot.com',
    iosClientId: '742438237263-85g7kfkctv6umatd36et4fp1mpeta6mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutriLens',
  );
}
